$(document).ready(function() {

	//hide the guide list links and the quick icket links by default and giving them their exanding functions
      $('#guide_list').hide();
	  $('#guide').click(function(){
		$('#guide_list').slideToggle();
	  });
	  
	  $('#quick_tickets_list').hide();
	  $('#quick_tickets').click(function(){
		$('#quick_tickets_list').slideToggle();
	  });
	  

$( "#application_name" ).autocomplete({
    source: [ 
".NET",
"278 EDI Transactions",
"7-ZIP",
"Able2Extract",
"Above the Branches",
"Absolute CompuTrace",
"Access",
"Acrobat",
"ACT",
"AD / DNS / WINS",
"AdminiSource",
"Adobe Reader",
"Agent Desktop (CAD)",
"Aircard",
"Alegeus",
"Altiris",
"Analytics Report Manager",
"Appeals and Grievances Application (A&G)",
"Application Compatibility Toolkit (ACT)",
"Apropos",
"ArcServe",
"Articulate Presenter",
"Articulate Studio for PowerPoint",
"ASG-Cypress",
"ASO",
"Attachmate Extra",
"Auto Enrollment",
"AutoAdjust Utility",
"AutoData",
"Automate BPA ",
"Automated Voice Response System (AVRS)",
"AutoQ",
"Autosys",
"Backup MPLS Circuits",
"Barcode Magician Plus",
"BDS Desktop Watch",
"Beyond Compare",
"BGInfo",
"Bindview",
"Biscom",
"Bizmanualz",
"BizTalk",
"Blackberry",
"BlackBerry Desktop",
"BlackBerry Drivers",
"BMC Remedy",
"Bring Your Own Device (BYOD)",
"Bulk Mailer",
"Bulletin Board System (BBS)",
"Business Document Server (BDS)",
"CA ERwin",
"CA Output Management Web Document Viewer",
"Cactus",
"Calendar Printing Assistant",
"California Children Services (CCS)",
"Call Center / IVR",
"Call Management Supervisor (CMS)",
"Call Manager",
"Camtasia",
"Captivate",
"Capture Manager",
"Care Enhance",
"CareAdvance",
"CareEnhance Review Manager",
"CareEvolution",
"Case Management Extraction Tool (CMET)",
"CATNET",
"CCA Client",
"CCH Teammate",
"Centers for Medicare and Medicaid Services (CMS)",
"Central Medical Chart Management System (CMCM)",
"Central SQL",
"Centricity Practice Solutions (CPS)",
"Change Management Database (CMD)",
"Check Point Pointsec",
"Check Printing and Signing",
"Check Tracer",
"Checkpoint",
"Cincom",
"Cisco Agent Desktop",
"Cisco Anyconnect Mobility Client",
"Cisco IP Phone",
"Cisco IronPort Email Security",
"Cisco MeetingPlace",
"Cisco Outbound Dialer",
"Cisco Unified Communications Manager (CUCM)",
"Cisco Unified Intelligence Center",
"Cisco Unified Personal Communicator (CUPC)",
"Cisco Unified Presenter",
"Cisco Unified Video Advantage",
"Cisco Virtual Private Network (VPN)",
"Cisco Voice Portal",
"Cisco Works Licenses",
"Citrix",
"Citrix Online Plugin",
"Citrix Receiver",
"Citrix Servers",
"Claims and Encounter Management System (CEMS)",
"Claims Editor",
"Claims Recovery",
"Claims Viewer",
"Claims Workflow",
"Clear Coverage",
"ClearCase",
"Client Access",
"Clinical Authorization System (CAS)",
"Clinical CareAdvance (CCA)",
"CM Report",
"CodeWright",
"Cogniview PDF2XL",
"Compliance HIPAA Management Program (CHAMP)",
"Concur iPremier",
"Configuration Information Management (CIM) Workflow",
"Contact Manager",
"Convery Compliance Systems COTS / Taxport",
"Coordination of Benefits (COB)",
"Core Impact",
"CPS BI Analytics",
"CPS Plugin",
"CPS Reporting (SSRS)",
"Crystal Reports",
"CUPC",
"Customer Information Control System (CICS)",
"Customer Information Control System (CICS) NJP",
"CVS, CVS Caremark",
"Cypress",
"CypressWeb",
"DameWare",
"Data Loss Prevention (DLP)",
"Database Security",
"Datawatch BDS",
"DB Masking",
"DB2 Connect",
"DBProtect",
"DCR",
"Decision Support System (DSS)",
"Denials",
"Desktop Hardware",
"DHSS",
"Diplomat",
"Division of Financial Responsibility (DOFR)",
"Domain Assessment Tool (DAT)",
"DR Datacenter - Development Network",
"DR Datacenter - DMZ Network",
"DR Datacenter - Production Network",
"ECC",
"E-Centaurus",
"EDI Alternate",
"EDIFECS",
"EDIGateway",
"eG",
"Electronic Claims sFTP",
"Electronic Media Claims Tracking/Accounting",
"Emptoris Contract Management",
"EMR Link",
"EMR Link (MHI)",
"EMR Patient Portal",
"EncoderPro",
"Enghouse",
"Enterprise Library",
"Enterprise Project Portfolio Management (EPPM)",
"Enterprise Resource Planning (ERP)",
"EnterpriseOne",
"EquityEdge",
"eScript Messenger (eSM)",
"ETL Interfaces",
"EV",
"eVault",
"Exceed",
"Excel",
"Exchange",
"Exchange 2007 Email",
"Expression Blend",
"Facility Site Review (FSR)",
"Faxcom",
"FES Alternate",
"FFS Claims History",
"File Print",
"File Transfer Service",
"FileNet",
"FileZilla",
"Firewall",
"FIS",
"Flash Player",
"FlexiInternational",
"FlexPrint",
"Forefront Identity Manager (FIM)",
"FS Pro",
"Future Vision",
"GAP: Classification UI",
"GAP: COC",
"Gap: Copay",
"Gap: Custom",
"Gap: LockIn",
"Gap: PHIP",
"Gap: Reversal and Adjustment",
"GAP: Unverified COB",
"Geocoder",
"GIMP",
"GoToMeeting",
"GSS Infrastructure",
"HBS Pharmacy",
"Health Business System (HBS) Point of Sale",
"Health Care Insight (HCI)",
"HP Quality Center",
"Human Resources Information System (HRIS)",
"Hummingbird Exceed",
"IBM ClearCase, IBM Rational ClearCase",
"IBM DB2 Connect",
"IDM",
"IEX TotalView Workforce Management",
"IEX Workforce Management",
"iLearn",
"ImageNow",
"Impact 360 Quality Monitoring",
"Imperva",
"Ingenix EncoderPro",
"Intelicode",
"Interactive Voice Response (IVR)",
"Internet Circuits",
"Internet Explorer",
"Interqual",
"Intranet",
"Intranet Sharepoint Sites",
"Investintech Able2Extract",
"iPay",
"Ipswitch WS_FTP",
"iRequest",
"IronPort",
"Java Bean Open Source Software (JBoss)",
"Java Runtime Environment (JRE)",
"JAWS",
"JBoss Application Server",
"JDEdwards",
"KeePass Password Safe",
"Kenexa Prove It",
"Kofax Capture",
"Kronos",
"Laboratory Information System (Labdaq)",
"lamedicaid.com",
"Laserfiche",
"LearnNowPlus",
"Lenel",
"Letter Manager",
"Link Logic (DTS)",
"Link Logic (DTS) (MHI)",
"LiteSpeed",
"LVM Nurse Advice Line (NAL)",
"Manage Care (GeoAccess)",
"Mantis",
"MAPD Capitation Engine",
"MAPD Enrollment Engine",
"Master Client Index (MCI)",
"Master Provider File (MPF) Viewer",
"McKesson",
"MeadCo ScriptX",
"MEDai",
"Medicaid Accountability Reporting System (MARS)",
"Medicaid Eligibility Verification System (MEVS)",
"Medical Chart",
"MedInsight Health Cost Guidelines (HCG) Grouper",
"MedInsight ProDiver",
"MeetingPlace",
"Member Utility",
"Member360",
"Mercator",
"MicroDyn",
"Microsoft .NET Framework",
"Microsoft Access",
"Microsoft Application Compatibility Tool (ACT)",
"Microsoft Calendar Printing Assistant",
"Microsoft Enterprise Library",
"Microsoft Excel",
"Microsoft Expression Blend",
"Microsoft Internet Explorer",
"Microsoft Office",
"Microsoft Outlook",
"Microsoft PowerPoint",
"Microsoft Project",
"Microsoft Publisher",
"Microsoft Remote Desktop Connection",
"Microsoft SharePoint Designer",
"Microsoft Silverlight",
"Microsoft Visio",
"Microsoft Visual Basic",
"Microsoft Visual SourceSafe",
"Microsoft Visual Studio",
"Microsoft Visual Studio Team Explorer",
"Microsoft Word",
"Misdirected Claims",
"Mobile Iron",
"Molina Connect",
"Molina Eligibility Gateway (MEG)",
"Molina Online Service Request",
"Molina Store",
"MolinaClinics.com",
"MolinaHeathCare.com",
"MolinaMedicare.com",
"MoveitDMZ",
"MPLS Circuits",
"Multitrans",
"My Health PAS (MHP) Online Claims/PA Entry/EDI upload",
"NetBackup",
"Network Infrastructure",
"Network Virtual Drives",
"Networx",
"NICE Customer Interaction Management",
"Nitro PDF",
"NJMMIS Electronic Claims Portal",
"NJMMIS Firewall",
"NJMMIS Site File Server and Printer Management",
"NJMMIS WEB (EMEVS)",
"NM Datacenter - Development Network",
"NM Datacenter - DMZ Network",
"NM Datacenter - Production Network",
"NMTPA Auth Daily Extract",
"Nolio",
"Notepad++",
"OADES Claims Retrieval",
"OEMS Production Support Tool",
"Office",
"Office Compatibility Pack",
"Omnicaid",
"OnBase",
"Onvicord",
"Open Text",
"Openpages",
"Operational Data Store (ODS)",
"Optically Assisted Data Entry System (OADES)",
"Oracle AIA PIP (SOA Middleware)",
"Oracle Business Intelligence Enterprise Edition (OBIEE)",
"Outbound Encounters Management System (OEMS)",
"Outlook",
"P4P Reports",
"PA",
"Pacific Coast Pharmacy",
"PaperVision",
"PBX",
"PDF Pro",
"PDF2XL",
"PDFCreator",
"PEA - Online Provider Enrollment",
"Performance Analysis",
"Pharmacy Online System (POS)",
"Pharmacy Rebate Information Management System (PRIMS)",
"Plastic ID Card (PID)",
"Potential Quality of Care (PQOC) Database",
"PowerPoint",
"Precert",
"Premium Reconciliation",
"Pretty Good Privacy (PGP)",
"Primary MPLS Circuits",
"Primavera",
"Printer Hardware",
"Privia",
"Process Manager - .NET",
"Process Manager - Vanetica 3i",
"Proclarity Web Professional",
"Proform Designer",
"Project",
"Provider Contract Utility",
"Provider Correspondence Tracking",
"Provider Dispute Resolution (PDR)",
"Provider Enrollment Tracking System (PETS)",
"Provider Incentive Program (PIP)",
"Provider Network Crosswalk Web Site",
"Publisher",
"PuTTY",
"QNXT",
"QNXT Entitlement Review Portal",
"QNXT Mass Adjudication",
"QNXT Payment Process (Run by ITOPS)",
"QNXT Reporting (CRA)",
"QNXT Reporting (SSRS)",
"QNXT Test Environment",
"QNXT Web Base Request",
"QSI (HEDIS)",
"Quality Center",
"Quality Spectrum (HEDIS)",
"R for Windows",
"Rational ClearCase",
"Rational Quality Management System (RQMS)",
"Recipient Eligibility Verification System (REVS)",
"Redbook (Red Book)",
"Reflections",
"Remote Desktop Connection",
"RightFax",
"Rimage",
"Risk Navigator Clinical",
"RS Client Print",
"RStudio",
"RxAmerica",
"RxClaim",
"RxGenesys",
"RxPA",
"SalesForce.com (SFDC)",
"ScriptX",
"Secure Authentication for EnCase (SAFE)",
"Security Menu",
"SharePoint",
"SharePoint 2010 Power Pivot",
"SharePoint Collaboration Sites",
"SharePoint Designer",
"Shavlik",
"Silverlight",
"Site File and Print Servers",
"SMARTS",
"SmartTrack",
"Snagit",
"SOA Web Services",
"Soft phone",
"SourceSafe",
"SQL Server",
"SSIS Eportal Packages",
"SSIS Packages",
"SSL and Remote VPN",
"Statistical Analysis System (SAS)",
"Streaming Video",
"Supervisor Desktop (CSD)",
"Symantec Compliance Control Suite (CCS)",
"Symantec Endpoint Protection (SEP)",
"Symantec Enterprise Vault",
"Symantec Security Information Manager (SSIM)",
"Symon Deskview",
"Syntellect Resource Manager",
"System Center Operations Management (SCOM)",
"Team Foundation Server (TFS)",
"Telepresence",
"The Pharmacy Connection (TPC)",
"Third Party Liability (TPL)",
"Toad for Oracle",
"TPA - Online Trading Partner",
"TPS Dashboard",
"TSO",
"UC4",
"Ultraedit",
"UMK2",
"Unified Contact Center Enterprise (UCCE)",
"Unified Intelligent Contact Management (ICM)",
"Unity Messaging",
"User Management Resource Administrator (UMRA)",
"Variphy",
"vBlock",
"Verizon Broadband Card",
"Virtual Desktop Infrastructure (VDI)",
"Virtual PC",
"Visio",
"Visio Viewer",
"Visual Basic",
"Visual SourceSafe",
"Visual Studio",
"Visual Studio Team Explorer",
"VLC Media Player",
"Vmware / vSphere",
"Voice Over Internet Protocol (VOIP)",
"Voicemail",
"VZ Manager",
"VZAccess Manager",
"Waiver Request Management System (WRMS)",
"Web mail, webmail",
"Web Portal - Admin/Support",
"Web Portal - File Exchange Services",
"Web Portal - Interactive Voice Recognition (IVR)",
"Web Portal - Members",
"Web Portal - Provider",
"Web Portal - Provider Online Directory (POD)",
"Web Portal - Reporting Tool",
"Web Portal - Reports",
"Web Portal (ePortal)",
"WebDAT",
"WebEx",
"WebEx Connect",
"WebEx Productivity Tools",
"Webinar",
"Websense Web Filter",
"Websphere",
"WebStrat",
"WebTrends Web Analytics - Dotcoms",
"WebTrends Web Analytics - Intranet",
"Whats UP Gold",
"Windows",
"Windows Secure Copy",
"WinSCP",
"WinZip",
"Wipro",
"Wireless Network Licenses and Access Points",
"Witness Actionable Solutions",
"Witness IP Contact Center and Quality Monitoring",
"Word",
"Workshare",
"Worldox",
"WRQ Reflection",
"WS_FTP",
"XenApp Data Collector"
	]
});

$("#application_category").autocomplete({
	source : [
	"Applications  - Corporate Business > Change Management Database (CMD)",
"Applications - Corporate Business",
"Applications - Corporate Business > Altiris",
"Applications - Corporate Business > CCH TeamMate",
"Applications - Corporate Business > Concur Premier",
"Applications - Corporate Business > Emptoris",
"Applications - Corporate Business > Equity Edge",
"Applications - Corporate Business > FileNet",
"Applications - Corporate Business > ImageNow",
"Applications - Corporate Business > Kronos",
"Applications - Corporate Business > Microsoft Exchange (Email)",
"Applications - Corporate Business > Microsoft SharePoint (Intranet)",
"Applications - Corporate Business > MultiTrans Prism",
"Applications - Corporate Business > OpenPages",
"Applications - Corporate Business > Oracle Business Intelligence Enterprise (OBIE)",
"Applications - Corporate Business > Oracle Primavera",
"Applications - Corporate Business > Other",
"Applications - Corporate Business > Rational ClearCase",
"Applications - Corporate Business > Statistical Analysis System (SAS)",
"Applications - Corporate Business > User Management Resource Administrator (UMRA)",
"Applications - Desktop",
"Applications - Desktop > 7-ZIP",
"Applications - Desktop > Adobe Acrobat [*]",
"Applications - Desktop > Adobe Captivate [*]",
"Applications - Desktop > Adobe Flash Player",
"Applications - Desktop > Adobe Reader",
"Applications - Desktop > Articulate Powerpoint Template [*]",
"Applications - Desktop > Articulate Presenter",
"Applications - Desktop > Attachmate Extra X-treme [*]",
"Applications - Desktop > Beyond Compare [*]",
"Applications - Desktop > BlackBerry Desktop Manager",
"Applications - Desktop > BlackBerry Device Drivers",
"Applications - Desktop > BMC Remedy",
"Applications - Desktop > CA Erwin Data Modler [*]",
"Applications - Desktop > Checkpoint Pointsec",
"Applications - Desktop > Cisco Agent Desktop (CAD)",
"Applications - Desktop > Cisco Supervisor Desktop (CSD)",
"Applications - Desktop > Cisco Unified Video Advantage",
"Applications - Desktop > Cisco Virtual Private Network (VPN)",
"Applications - Desktop > Citrix",
"Applications - Desktop > Citrix Online Plugin",
"Applications - Desktop > Citrix Receiver",
"Applications - Desktop > Code Wright",
"Applications - Desktop > Cogniview PDF2XL [*]",
"Applications - Desktop > Crystal Reports [*]",
"Applications - Desktop > CypressWeb",
"Applications - Desktop > DameWare [*]",
"Applications - Desktop > Datawatch Business Document Server (BDS)",
"Applications - Desktop > FileZilla",
"Applications - Desktop > GIMP Image Editor",
"Applications - Desktop > HP Quality Center (QC) [*]",
"Applications - Desktop > Hummingbird Exceed [*]",
"Applications - Desktop > IBM DB2 Connect [*]",
"Applications - Desktop > Ingenix Encoder Pro",
"Applications - Desktop > IronPort Secure Email",
"Applications - Desktop > KeePass Password Safe",
"Applications - Desktop > Laserfiche - Document Management",
"Applications - Desktop > McKesson Claim Check [*]",
"Applications - Desktop > Meadco ScriptX Action",
"Applications - Desktop > Microsoft Access",
"Applications - Desktop > Microsoft Calendar Printing Assistant",
"Applications - Desktop > Microsoft Enterprise Library",
"Applications - Desktop > Microsoft Expression Blend [*]",
"Applications - Desktop > Microsoft Internet Explorer",
"Applications - Desktop > Microsoft Office",
"Applications - Desktop > Microsoft Office - Excel",
"Applications - Desktop > Microsoft Office - Outlook (Email)",
"Applications - Desktop > Microsoft Office - PowerPoint",
"Applications - Desktop > Microsoft Office - Word",
"Applications - Desktop > Microsoft Office Compatability Pack",
"Applications - Desktop > Microsoft Project [*]",
"Applications - Desktop > Microsoft Publisher",
"Applications - Desktop > Microsoft Remote Desktop Connection",
"Applications - Desktop > Microsoft SharePoint Designer",
"Applications - Desktop > Microsoft Virtual PC",
"Applications - Desktop > Microsoft Visio [*]",
"Applications - Desktop > Microsoft Visio Viewer",
"Applications - Desktop > Microsoft Visual Basic",
"Applications - Desktop > Microsoft Visual SourceSafe (VSS)",
"Applications - Desktop > Microsoft Visual Studio",
"Applications - Desktop > Microsoft Visual Studio Team Explorer",
"Applications - Desktop > Microsoft Windows",
"Applications - Desktop > Nitro PDF Pro [*]",
"Applications - Desktop > Notepad+",
"Applications - Desktop > OADES Claims Retrieval [*]",
"Applications - Desktop > Other",
"Applications - Desktop > PDF Creator",
"Applications - Desktop > Pretty Good Privacy (PGP) Desktop [*]",
"Applications - Desktop > ProClarity Web Professional",
"Applications - Desktop > Putty",
"Applications - Desktop > R for Windows",
"Applications - Desktop > Reflections",
"Applications - Desktop > RightFax - Desktop Faxing",
"Applications - Desktop > RS Client Print",
"Applications - Desktop > Sun Java Runtime Environment (JRE)",
"Applications - Desktop > Symantec Endpoint Protection (SEP)",
"Applications - Desktop > Symantec Enterprise Vault",
"Applications - Desktop > Syntellect Resource Manager",
"Applications - Desktop > TechSmith Camtasia [*]",
"Applications - Desktop > TechSmith SnagIt [*]",
"Applications - Desktop > Toad for Oracle [*]",
"Applications - Desktop > TotalView Workforce Management",
"Applications - Desktop > UltraEdit [*]",
"Applications - Desktop > Verint Impact 360 Quality Monitoring (QM)",
"Applications - Desktop > Verint Witness Actionable Solutions",
"Applications - Desktop > VLC Media Player",
"Applications - Desktop > Web.Strat",
"Applications - Desktop > Windows Secure CoPy (WinSCP)",
"Applications - Desktop > WinZip [*]",
"Applications - Desktop > WRQ Reflection",
"Applications - Health Care",
"Applications - Health Care > Appeals & Grievances (A&G)",
"Applications - Health Care > BizTalk",
"Applications - Health Care > CACTUS",
"Applications - Health Care > California Children Services (CCS)",
"Applications - Health Care > Care Enhance InterQual",
"Applications - Health Care > Case Management Extraction Tool (CMET)",
"Applications - Health Care > Cincom",
"Applications - Health Care > Claims and Encounters Management System (CEMS)",
"Applications - Health Care > Claims Audit Tool .NET (CATNET)",
"Applications - Health Care > Claims Editor",
"Applications - Health Care > Claims Recovery",
"Applications - Health Care > Claims Viewer",
"Applications - Health Care > Clinical CareAdvance",
"Applications - Health Care > Contract Information Management (CIM) Workflow",
"Applications - Health Care > Customer Information Control System (CICS)",
"Applications - Health Care > Decision Support Systems (DSS)",
"Applications - Health Care > Division of Financial Responsibility (DOFR)",
"Applications - Health Care > Domain Assessment Tool (DAT)",
"Applications - Health Care > Electronic Medical Records (EDI)",
"Applications - Health Care > ePortal - File Exchange Services",
"Applications - Health Care > ePortal - Member Self Service",
"Applications - Health Care > Facility Site Review (FSR)",
"Applications - Health Care > HEDIS Server",
"Applications - Health Care > HMS - Coordination of Benefits (COB)",
"Applications - Health Care > HP Quality Center (QC)",
"Applications - Health Care > K2 Claims Workflow",
"Applications - Health Care > LVM Nurse Advice Line (NAL)",
"Applications - Health Care > Master Provider File (MPF) Viewer",
"Applications - Health Care > Medicare Advantage Prescription Drug (MAPD)",
"Applications - Health Care > Medinsight",
"Applications - Health Care > Member Utility",
"Applications - Health Care > Misdirected Claims",
"Applications - Health Care > Molina Eligibility Gateway (MEG)",
"Applications - Health Care > NetworX Modeler",
"Applications - Health Care > Operational Data Store (ODS)",
"Applications - Health Care > Outbound Encounters Management System (OEMS)",
"Applications - Health Care > Pacific Coast Pharmacy",
"Applications - Health Care > Pay for Performance (P4P)",
"Applications - Health Care > PETS",
"Applications - Health Care > Point of Sale (POS)",
"Applications - Health Care > Premium Reconciliation",
"Applications - Health Care > Provider Contract Utility",
"Applications - Health Care > Provider Dispute Resolution (PDR) Database",
"Applications - Health Care > salesforce.com (SFDC)",
"Applications - Health Care > UMK2",
"Applications - Health Care > Waiver Request Management System (WRMS)",
"Applications - Health Care > www.molinaclinics.com",
"Applications - Health Care > www.molinamedicare.com",
"Applications - Health Care Systems",
"Applications - Healthcare",
"Applications - Healthcare > Risk Navigator Clinical",
"Applications - Health Care > Appeals & Grievances (A&G)",
"ERP",
"Hardware",
"Hardware > Mobile Device - Blackberry",
"Hardware > Printer",
"Hardware > VDI",
"HD - Desktop Support",
"Human Resources > Above the Branches",
"IT Use Only > Core Systems",
"IT Use Only > Core Systems > Adminisource/ERA/EFT",
"IT Use Only > Core Systems > Care Advance",
"IT Use Only > Core Systems > CHAMP/PDR",
"IT Use Only > Core Systems > EMR",
"IT Use Only > Core Systems > TFS",
"IT Use Only > DBA",
"MMS",
"Network & Telephony",
"Network & Telephony > Autosys Dev",
"Network & Telephony > Call Scripting",
"Network & Telephony > Centricity Practice Solution (CPS)",
"Network & Telephony > Cisco IP Phone",
"Network & Telephony > Cisco TelePresence",
"Network & Telephony > Cisco Unified CallManager",
"Network & Telephony > Cisco Virtual Private Network (VPN)",
"Network & Telephony > Cisco Webex",
"Network & Telephony > Firewall",
"Network & Telephony > Interactive Voice Response (IVR)",
"Network & Telephony > Microsoft SQL Server",
"Network & Telephony > System Center Operations Manager (SCOM)",
"Network & Telephony > Voicemail",
"Network & Telephony > VZAccess Manager",
"Network & Telephony > WebSense",
"Network Engineering",
"Ops & Maintenance",
"QNXT\Troubleshooting",
"Rational Tools > RQMS",
"Software > PC Applications"

	]
});

$("#eportal_location").autocomplete({
	source: [ "CA - California",
		"FL - Florida",
		"IL - Illinois",
		"MI - Michigan",
		"MO - Missouri",
		"NM - New Mexico",
		"OH - Ohio",
		"TX - Texas",
		"UT - Utah",
		"WA - Washington",
		"WI - Wisconsin",
		"Medicare"
	]});

$( "#contact_location" ).autocomplete({
    source: [ "MMS - Remote",
			"CA - SMO Clinic",
			"CA - 200 Molina Center",
			"CA - 300 Molina Center",
			"CA - Colton",
			"CA - Golden Shore",
			"CA - Hughes Way",
			"CA - Landmark",
			"CA - Long Beach",
			"CA - Sacramento Regional",
			"CA - San Diego Regional",
			"DC - Washington DC Legal",
			"FL - Miami Doral",
			"FL - West Palm Beach",
			"FL - Tampa",
			"FL - Tallahassee",
			"IN - Merrillville",
			"ID - Boise",
			"LA - Ste 110 Baton Rouge",
			"LA - Ste 250 Baton Rouge",
			"ME - Augusta",
			"MI - Troy",
			"MO - Jefferson City",
			"MO - Kansas City",
			"MO - St Louis",
			"NJ - Trenton",
			"NM - Albuquerque",
			"NM - Santa Fe",
			"OH - Columbus",
			"TX - San Antonio",
			"TX - Houston",
			"TX - Dallas",
			"TX - Edinburg/McAllen/Hidalgo",
			"TX - El Paso",
			"TX - Irving",
			"TX - Laredo",
			"TX - McAllen",
			"TX - Park Row Plaza",
			"UT - Midvale",
			"VA - Arlington",
			"VA - Herndon",
			"VA - VA Clinics",
			"VA - Glen Allen",
			"VA - Virginia Beach",
			"VA - North County",
			"VA - South County",
			"VA - Reston",
			"WA - 17th Ave Bothell",
			"WA - Bothell",
			"WA - Compass Clinic",
			"WA - Spokane",
			"WA - South Everett",
			"WV - Charleston",
			"WI - West Allis" ]
});
				  
	  

	  
	  //set up new/existing tabs
	  $(function() {    $( "#tabs" ).tabs();  });
	  
	  //ITSM Dialog Box
	  //make the submit button clickable and generate a dialog box containing the provided ticket details
	  $('#dialog-btn').click(function(){
			$('#dialog').empty();
			//content of the diolog box
			message = "<h4>CONTACT INFORMATION</h4>";
			message += "Name(s): " + document.form.contact_name.value + "<br />";
			message += "Number: " + document.form.contact_number.value + "<br />";
			message += "Location: " + document.form.contact_location.value + "<br /><br />";
	
			message += "<h4>TICKETING DETAILS</h4>";
			message += "Title: " + document.form.application_name.value + " - " + document.form.application_issue.value + "<br />";
			message += "Application Category: " + document.form.application_category.value + "<br />";
			message += "Ticket Type: " + document.form.type_of_ticket_out.value + "<br /><br />";
	
			message += "<h4>SEVERITY CALCULATIONS</h4>";
			message += "Impact: " + document.form.impact_out.value + "<br />";
			message += "Urgency: " + document.form.urgency_out.value + "<br /><br />";
	
			message += "<h4>CALL DETAILS</h4>";
			message += "Call Start: " + document.form.timer_start.value + "";
			message += "<br />Call End: " + document.form.timer_end.value + "";
			message += "<br />Elapsed: " + document.form.clock.value + "";
			message += "<br /><br />v1.4.0" + "";
	
	//attached buttons to the dialog box
	$('#dialog').append(message);
		$( "#dialog" ).dialog({      
			resizable: true,      
			modal: true,      
			buttons: {   
				"Service": function() {   //call function to submit form here
					alert("This button will open a new service ticket template in a new window");
				},     
				"Incident": function() {   //call function to submit form here
					alert("This button will open a new incident ticket template in a new window");
					//window.location.reload(); 
				},        
				"Close": function() {          
					$( this ).dialog( "close" );       
				}      
			}    
		});
	  });
	  
	  //ePortal Dialog Box
	  	  //make the submit button clickable and generate a dialog box containing the provided ticket details
	  $('#eportal-dialog-btn').click(function(){
			$('#eportal-dialog').empty();
			//content of the diolog box
			message = "<h4>CONTACT INFORMATION</h4>";
			message += "Name(s): " + $('#eportal_name').val() + "<br />";
			message += "Number: " + $('#eportal_number').val() + "<br />";
			message += "Location: " + $('#eportal_location').val() + "<br /><br />";
	
			message += "<h4>TICKETING DETAILS</h4>";
			message += "Title: " + $('#member_or_provider').val() + " - " + $('#eportal_issue_details').val() + "-" + $('#eportal_location').val()+ "<br />";
			message += $('#medicaid_or_medicare').val() + "<br/>";
			message += "Tax ID: " + $('#tax_id').val() + "<br/>";
			message += "User ID: " + $('#eportal_user_id').val() + "<br/>";
			message += "Facility: " + $('#facility_name').val() + "<br/>";
	
			//CALL DETAILS --- NOT WORKING YET.
			message += "<h4>CALL DETAILS</h4>";
			message += "Call Start: " + document.form.timer_start.value + "";
			message += "<br />Call End: " + document.form.timer_end.value + "";
			message += "<br />Elapsed: " + document.form.clock.value + "";
			message += "<br /><br />v1.4.0" + "";
			
			
	  //attached buttons to the diolog box
	$('#eportal-dialog').append(message);
		$( "#eportal-dialog" ).dialog({      
			resizable: true,      
			modal: true,      
			buttons: {   
				"Service": function() {   //call function to submit form here
					alert("This button will open a new service ticket template in a new window");
				},     
				"Incident": function() {   //call function to submit form here
					alert("This button will open a new incident ticket template in a new window");
					//window.location.reload(); 
				},        
				"Close": function() {          
					$( this ).dialog( "close" );       
				}      
			}    
		});
	  });
	  
	  //Tooltip Functionality
	  $( document ).tooltip();
	  
	  //Date Picker Functionality
	  $( "#datepicker" ).datepicker();
	  
	  //Setup Find Ticket Functionality
	  $("#find_ticket").click(function(){
		if($('#existing_ticket_number').val().length<1){
			alert("invalid ticket number");
		}else{
			window.open("http://support.molina.mhc/Aexhdsd/worker/default.aspx?cmd=viewItem&id="+$('#existing_ticket_number').val(), '_blank');
		}
	  });

});

